name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04' # for Tauri v1 you could use ubuntu-20.04.
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up the linux/windows runners.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
        # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.
        # You can remove the one that doesn't apply to your app to speed up the workflow a bit.

      - name: install frontend dependencies
        run: npm ci # change this to npm or pnpm depending on which one you use.

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
          releaseName: 'v__VERSION__' # tauri-action replaces \_\_VERSION\_\_ with the app version.
          releaseBody: |
            ## Download

            Choose the right file for your operating system:

            ### macOS
            - **JSON.Prettier___VERSION___aarch64.dmg** - Apple Silicon
            - **JSON.Prettier___VERSION___x64.dmg** - Intel
            - **JSON.Prettier_aarch64.app.tar.gz** - App Bundle for Apple Silicon
            - **JSON.Prettier_x64.app.tar.gz** - App Bundle for Intel

            ### Windows
            - **JSON.Prettier___VERSION___x64-setup.exe** - Standard Windows installer for 64-bit systems
            - **JSON.Prettier___VERSION___x64_en-US.msi** - Enterprise-friendly installation format

            ### Linux
            - **JSON.Prettier___VERSION___amd64.AppImage** - Universal Linux package that runs on most distributions
            - **JSON.Prettier___VERSION___amd64.deb** - For Ubuntu, Debian and derivatives
            - **JSON.Prettier-__VERSION__-1.x86_64.rpm** - For Red Hat, CentOS, Fedora and derivatives

            > **⚠️ IMPORTANT FOR macOS USERS**: macOS will show security warnings ("untrusted developer" or "app is damaged") on first launch.
            > Right-click the app and select "Open" to bypass this. For persistent issues, check our [Installation Guide](https://github.com/rebase/json-prettier/blob/main/INSTALLATION.md).
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
